plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- - "@semantic-release/changelog"
  - changelogFile: CHANGELOG.md
- - "@semantic-release/exec"
  - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
- "@semantic-release/gitlab"
- - '@semantic-release/git'
  - message: "RELEASE: ${nextRelease.version}"
    assets: ["CHANGELOG.md"]
branches:
- name: 'master'
- name: 'develop'
  prerelease: 'dev'
- name: '(release)(\/[0-9A-Za-z-]+)'
  prerelease: 'rc'