apiVersion: v1
kind: Service
metadata:
  name: basket-api
  labels:
    app: basket-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: basket-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-api
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
      - name: basket-api
        image: clmdevops/dotnet-microservice
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 80