apiVersion: v1
kind: Service
metadata:
  name: redissvc
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    protocol: TCP
    name: redis-port
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        